// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pm} from '../models';
import {context} from '../models';
import {gorm} from '../models';

export function CreatePM(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CreatePMGateway(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeletePM(arg1:number):Promise<void>;

export function DeletePMGateway(arg1:number):Promise<void>;

export function GetAllActivePMGateway():Promise<Array<pm.PMGateway>>;

export function GetAllPMGatewayFromDB():Promise<Array<pm.PMGateway>>;

export function SetPM(arg1:number,arg2:pm.PM):Promise<void>;

export function SetPMIsOk(arg1:number,arg2:boolean):Promise<void>;

export function SetPMIsRandom(arg1:number,arg2:boolean):Promise<void>;

export function SetPMKw(arg1:number,arg2:number):Promise<void>;

export function Startup(arg1:context.Context,arg2:gorm.DB):Promise<void>;

export function SyncPMGatewayWithDB():Promise<void>;
