// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePM(arg1, arg2, arg3) {
  return window['go']['pm']['App']['CreatePM'](arg1, arg2, arg3);
}

export function CreatePMGateway(arg1, arg2, arg3) {
  return window['go']['pm']['App']['CreatePMGateway'](arg1, arg2, arg3);
}

export function DeletePM(arg1) {
  return window['go']['pm']['App']['DeletePM'](arg1);
}

export function DeletePMGateway(arg1) {
  return window['go']['pm']['App']['DeletePMGateway'](arg1);
}

export function GetAllActivePMGateway() {
  return window['go']['pm']['App']['GetAllActivePMGateway']();
}

export function GetAllPMGatewayFromDB() {
  return window['go']['pm']['App']['GetAllPMGatewayFromDB']();
}

export function SetPM(arg1, arg2) {
  return window['go']['pm']['App']['SetPM'](arg1, arg2);
}

export function SetPMIsOk(arg1, arg2) {
  return window['go']['pm']['App']['SetPMIsOk'](arg1, arg2);
}

export function SetPMIsRandom(arg1, arg2) {
  return window['go']['pm']['App']['SetPMIsRandom'](arg1, arg2);
}

export function SetPMKw(arg1, arg2) {
  return window['go']['pm']['App']['SetPMKw'](arg1, arg2);
}

export function Startup(arg1, arg2) {
  return window['go']['pm']['App']['Startup'](arg1, arg2);
}

export function SyncPMGatewayWithDB() {
  return window['go']['pm']['App']['SyncPMGatewayWithDB']();
}
