// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hfreader} from '../models';
import {context} from '../models';
import {gorm} from '../models';

export function CreateReader(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteReader(arg1:number):Promise<void>;

export function GetAllDeviceFromDB():Promise<Array<hfreader.HFReader>>;

export function GetAllReader():Promise<Array<hfreader.HFReader>>;

export function SetReaderCardPresent(arg1:number,arg2:boolean):Promise<void>;

export function SetReaderConnection(arg1:number,arg2:boolean):Promise<void>;

export function SetReaderEpc(arg1:number,arg2:string):Promise<void>;

export function Startup(arg1:context.Context,arg2:gorm.DB):Promise<void>;

export function SyncReaderWithDB():Promise<void>;
