// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateReader(arg1, arg2, arg3, arg4) {
  return window['go']['hfreader']['App']['CreateReader'](arg1, arg2, arg3, arg4);
}

export function DeleteReader(arg1) {
  return window['go']['hfreader']['App']['DeleteReader'](arg1);
}

export function GetAllDeviceFromDB() {
  return window['go']['hfreader']['App']['GetAllDeviceFromDB']();
}

export function GetAllReader() {
  return window['go']['hfreader']['App']['GetAllReader']();
}

export function SetReaderCardPresent(arg1, arg2) {
  return window['go']['hfreader']['App']['SetReaderCardPresent'](arg1, arg2);
}

export function SetReaderConnection(arg1, arg2) {
  return window['go']['hfreader']['App']['SetReaderConnection'](arg1, arg2);
}

export function SetReaderEpc(arg1, arg2) {
  return window['go']['hfreader']['App']['SetReaderEpc'](arg1, arg2);
}

export function Startup(arg1, arg2) {
  return window['go']['hfreader']['App']['Startup'](arg1, arg2);
}

export function SyncReaderWithDB() {
  return window['go']['hfreader']['App']['SyncReaderWithDB']();
}
