// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deviceManager} from '../models';

export function CreateReader(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteReader(arg1:number):Promise<void>;

export function GetReader():Promise<Array<deviceManager.Device>>;
