// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateReader(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateReader'](arg1, arg2, arg3, arg4);
}

export function DeleteReader(arg1) {
  return window['go']['main']['App']['DeleteReader'](arg1);
}

export function GetReader() {
  return window['go']['main']['App']['GetReader']();
}
