// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deviceMqtt} from '../models';

export function CreateReader(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteReader(arg1:number):Promise<void>;

export function GetReader():Promise<Array<deviceMqtt.Device>>;

export function SetReaderCardPresent(arg1:number,arg2:boolean):Promise<void>;

export function SetReaderConnection(arg1:number,arg2:boolean):Promise<void>;

export function SetReaderEpc(arg1:number,arg2:string):Promise<void>;
